### ISSUE TITLE
Content of README.md and README_CN.md should be swapped

### ISSUE THREAD

**Issue by krhill82** [IoT-Technology/IoT-Toolkit#5]
The content of README.md is in Chinese, while the content of README_CN.md is in English.  Shouldn't the content of those two files be swapped? // README.md 内容为中文，README_CN 内容为英文。 不应该交换这两个文件的内容吗？

**Comment by sanshengshui** [comment]
Sorry, I will update and improve the English usage profile for the convenience of native English speakers

**Comment by sanshengshui** [comment]
I have updated the document, thank you
